### ISSUE TITLE
V1: problems 

### ISSUE THREAD

**Issue by t221f** [jyxi7676/STtools#11]
Hi again,
when running V1 step with your sample dataset, I get the error output below.
From what I understand, there seems to be a problem with the nrow and ncol counting in this step. When I checked this further, I noticed that the script does not allow to give --nrow or --ncol values at all.
Thanks a lot for all your amazing work!

Input
python3 $STHOME/sttools.py --run-steps V1 \
    --STtools $STHOME   \
    --predir $STOUT-test/visualization \
    --spatial $STOUT-test/spatialcoordinates.txt.gz \
    --ncpus 6 \
    --DGEdir $STDGEtest \
    --layout MiSeq \
    --green Alb \
    --red Mup20,Cyp2f2,Mup3,Serpina1e,Hsd17b13,Hpx,Hsd17b6,Pck1,Pigr,Ambp \
    --blue Cyp2e1,Cyp2c29,Cyp1a2,Mup11,Cyp2a5,Cyp2a50,Rgn,Hamp,Pon1,Slco1b2 \
    --tmpdir $STOUT-test/visualization \
    --buffer-size 10G;

Error output:
Processing (0,75) : 1_2219
here
/home/t141g/STtools/out-test/visualization/1/2219/features.tsv.gz
not exist
Calculate mean intensity of each color
Scale_factors = (200000000000.0, 200000000000.0, 200000000000.0)
Constructing an image of -115292150460684696 x -8762203435012036896
Traceback (most recent call last):
  File "/home/t141g/STtools/visualization/rgb-gene-image.py", line 223, in <module>
    data = np.zeros( (total_h, total_w, 3), dtype=np.uint8 )
ValueError: negative dimensions are not allowed
Traceback (most recent call last):
  File "/home/t141g/STtools/sttools.py", line 566, in <module>
    func()
  File "/home/t141g/STtools/sttools.py", line 528, in stepV1
    raise ValueError(f"ERROR in running {cmd7}, returning exit code {ret}")
ValueError: ERROR in running /usr/bin/python3 /home/t141g/STtools/visualization/rgb-gene-image.py -o /root/Sample_vis -d /home/t141g/STtools/out-test/visualization  -g Alb -b Cyp2e1,Cyp2c29,Cyp1a2,Mup11,Cyp2a5,Cyp2a50,Rgn,Hamp,Pon1,Slco1b2 -r Mup20,Cyp2f2,Mup3,Serpina1e,Hsd17b13,Hpx,Hsd17b6,Pck1,Pigr,Ambp --scale 20.0  --min-tpm 1000 --res 80 --layout /home/t141g/STtools/visualization/miseq_layout.tsv, returning exit code 256

**Comment by jyxi7676** [comment]
Hi，

I saw that you have 2219 tile for MiSeq. But I believe for MiSeq, there is
no tile 2219. Do you mind taking a look at what is your unique lane and
tiles? At the same time I will test something  by myself.

Thanks!
BR,
Jingyue

**Comment by t221f** [comment]
Hi and thanks for the fast reply,

Isn't the tile in the dataset 2106? Or is the dataset from HiSeq and not MiSeq?
Besides, the not exist error also occurred with a lot of other tiles before that.
Thanks and best wishes
Tobias

> Am 05.03.2022 um 20:14 schrieb jyxi7676 ***@***.***>:
> 
> ﻿
> Hi，
> 
> I saw that you have 2219 tile for MiSeq. But I believe for MiSeq, there is
> no tile 2219. Do you mind taking a look at what is your unique lane and
> tiles? At the same time I will test something by myself.
> 
> Thanks!
> BR,
> Jingyue
>

**Comment by liuchang707** [comment]
@t221f 
    Hi there, when running V1 step with the example data (tile 2106), I met the same problem as you mentioned above. So I would like to ask that have you fixed this problem finally? Thanks for your reply~

**Comment by liuchang707** [comment]
> @t221f Hi there, when running V1 step with the example data (tile 2106), I met the same problem as you mentioned above. So I would like to ask that have you fixed this problem finally? Thanks for your reply~

OK, I got it~ the example data is in */SampleSolo.out/GeneFull/ordered ~
